export var continentalUSConfig = {
  label: 'Continental U.S',
  region: 'continental_us',
  mapProperties: {
    label: 'Continental U.S',
    center: [40.979898, -81.474609],
    extent: [-132.97, 25.16, -62.49, 50.00],
    zoom: 4
  },
  chartInputs:  [
    {
      chartInputName: 'summary',
      ChartInputLabel: 'Summary',
    },
    {
      chartInputName: 'fishandwildlife',
      ChartInputLabel: 'Fish and Wildlife Inputs',
    },
    {
      chartInputName: 'asset',
      ChartInputLabel: 'Comunity Assets Inputs',
    },
    {
      chartInputName: 'threat',
      ChartInputLabel: 'Threats Inputs',
    }
],
    layerList:
      [
        {
          id: "CONUS_HubsTMS",
          layer: "Hubs TMS",
          label: "Resilience Hubs",
          apikey: 'hubs',
          hubsapikey: 'hubs',
          chartLabel: 'Resilience Hubs',
          chartLegendValues: 10,
          chartCSSColor: {
            0: '#E9ECEF',
            1: '#ffc500',
            2: '#f9b500',
            3: '#f3a400',
            4: '#ed9400',
            5: '#e78300',
            6: '#e07000',
            7: '#d95e00',
            8: '#d14c00',
            9: '#ca3600',
            10: '#c21500',
          },
          chartDriver: false,
          chartSummary: true,
          chartOrder: 1,
          chartInputName: 'summary',
          ChartInputLabel: 'Summary',
          chartCSSSelector: 'hubs',
          chartMaxValue: 11,
          chartMinValue: 0,
          chartScale: 0,
          chartScaleGroups: 1,
          chartNoDataOverRide: 1,
          url: "https://tiles.resilientcoasts.org/HubsIndexTiles/{z}/{x}/{y}.png",
          attribution: "NFWF 2020",
          format: "image/png",
          tileSize: 256,
          transparent: true,
          opacity: 0.75,
          zIndex: 9000,
          crs: L.CRS.EPSG3857,
          maxNativeZoom: 13,
          tms: false,
          legend: "hub",
          description: "Areas of open lands and protected space that may be suitable for resilience-building efforts. Hubs are ranked by priority, given the level of exposure that nearby assets have to flood-related threats and the presence and abundance of fish and wildlife species within and surrounding the Hub.",
          source: 'regional',
          region: 'continental_us'
        },
        {
          id: "CONUS_ExposureTMS",
          layer: "Exposure TMS",
          label: "Community Exposure Index",
          apikey: 'exposure',
          hubsapikey: 'exposure',
          chartLabel: 'Community Exposure',
          chartLegendValues: 10,
          chartCSSColor: {
            0: '#E9ECEF',
            1: '#1f6e6e',
            2: '#3d8282',
            3: '#7dad9c',
            4: '#b7d4b2',
            5: '#e9f2bb',
            6: '#f5e9a9',
            7: '#dbba7a',
            8: '#b08042',
            9: '#9b5526',
            10: '#633319',
          },
          chartDriver: false,
          chartSummary: true,
          chartOrder: 2,
          chartInputName: 'summary',
          ChartInputLabel: 'Summary',
          chartCSSSelector: 'exposure',
          chartMaxValue: 11,
          chartMinValue: 0,
          chartScale: 0,
          chartScaleGroups: 1,
          chartNoDataOverRide: 1,
          url: "https://tiles.resilientcoasts.org/ExposureIndexTiles/{z}/{x}/{y}.png",
          attribution: "NFWF 2020",
          format: "image/png",
          tileSize: 256,
          transparent: true,
          opacity: 0.75,
          zIndex: 9000,
          crs: L.CRS.EPSG3857,
          maxNativeZoom: 13,
          tms: false,
          legend: "exposure",
          description: "The product of the Asset and Threat Indices, which suggests areas on the landscape where community assets are potentially exposed to flood-related threats.",
          source: 'regional',
          region: 'continental_us'
        },
        {
          id: "CONUS_AssetsTMS",
          layer: "Assets TMS",
          label: "Community Asset Index",
          apikey: 'asset',
          hubsapikey: 'asset',
          chartLabel: 'Community Asset',
          chartLegendValues: 10,
          chartCSSColor: {
            0: '#E9ECEF',
            1: '#b6edf0',
            2: '#98d2ed',
            3: '#7cbbeb',
            4: '#5ca3e6',
            5: '#368de3',
            6: '#2176d9',
            7: '#2259c7',
            8: '#1d3eb5',
            9: '#1727a3',
            10: '#090991',
          },
          chartDriver: false,
          chartSummary: true,
          chartOrder: 3,
          chartInputName: 'summary',
          ChartInputLabel: 'Summary',
          chartCSSSelector: 'asset',
          chartMaxValue: 11,
          chartMinValue: 0,
          chartScale: 0,
          chartScaleGroups: 1,
          chartNoDataOverRide: 1,
          url: "https://tiles.resilientcoasts.org/AssetsIndexTiles/{z}/{x}/{y}.png",
          attribution: "NFWF 2020",
          format: "image/png",
          tileSize: 256,
          transparent: true,
          opacity: 0.75,
          zIndex: 9000,
          crs: L.CRS.EPSG3857,
          maxNativeZoom: 13,
          tms: false,
          legend: "asset",
          description: "Index of community assets critical to the recovery of an area and human population. High values suggest areas with a higher, cumulative prevalence of community assets on the landscape.",
          source: 'regional',
          region: 'continental_us'
        },
        {
          id: "CONUS_ThreatsTMS",
          layer: "Threats TMS",
          label: "Threat Index",
          apikey: 'threat',
          hubsapikey: 'threat',
          chartLabel: 'Threat',
          chartLegendValues: 10,
          chartCSSColor: {
            0: '#E9ECEF',
            1: '#ffebd6',
            2: '#f7d7bc',
            3: '#f0c0a1',
            4: '#eba988',
            5: '#e3906f',
            6: '#de775b',
            7: '#d65d45',
            8: '#d14030',
            9: '#c9251c',
            10: '#c40a0a',
          },
          chartDriver: false,
          chartSummary: true,
          chartOrder: 4,
          chartInputName: 'summary',
          ChartInputLabel: 'Summary',
          chartCSSSelector: 'threat',
          chartMaxValue: 11,
          chartMinValue: 0,
          chartScale: 0,
          chartScaleGroups: 1,
          chartNoDataOverRide: 1,
          url: "https://tiles.resilientcoasts.org/ThreatsIndexTiles/{z}/{x}/{y}.png",
          attribution: "NFWF 2020",
          format: "image/png",
          tileSize: 256,
          transparent: true,
          opacity: 0.75,
          zIndex: 9000,
          crs: L.CRS.EPSG3857,
          maxNativeZoom: 13,
          tms: false,
          legend: "threat",
          description: "Index of flood-related datasets, including storm surge scenarios and landscape characteristics that exacerbate flood potential. High values in the Index represent those areas on the landscape where there are multiple high values of individual inputs.",
          source: 'regional',
          region: 'continental_us'
        },

        {
          id: "CONUS_FishAndWildlifeTMS",
          layer: "FishAndWildlife TMS",
          label: "Fish and Wildlife Index",
          apikey: 'wildlife',
          hubsapikey: 'fishandwildlife',
          chartLabel: 'Fish and Wildlife',
          chartLegendValues: 6,
          chartCSSColor: {
            0: '#E9ECEF',
            1: '#EEE7F8',
            2: '#E9BBCB',
            3: '#DB90A6',
            4: '#D27C99',
            5: '#B7528A',
            6: '#7E33A8',
          },
          chartDriver: false,
          chartSummary: true,
          chartOrder: 5,
          chartInputName: 'summary',
          ChartInputLabel: 'Summary',
          chartCSSSelector: 'fishandwildlife',
          chartMaxValue: 7,
          chartMinValue: 0,
          chartScale: 0,
          chartScaleGroups: 1,
          chartNoDataOverRide: 1,
          url: "https://tiles.resilientcoasts.org/CombinedWildlifeIndexTiles/{z}/{x}/{y}.png",
          attribution: "NFWF 2020",
          format: "image/png",
          tileSize: 256,
          transparent: true,
          opacity: 0.75,
          zIndex: 9000,
          crs: L.CRS.EPSG3857,
          maxNativeZoom: 13,
          tms: false,
          legend: "fishandwildlife",
          description: "Fish and wildlife needs a description currently this text is just a placeholder.",
          source: 'fishandwildlife',
          region: 'continental_us'
        },
        {
          id: "CONUS_AquaticTMS",
          layer: "Aquatic TMS",
          label: "Aquatic Index",
          apikey: 'aquatic',
          hubsapikey: 'aquatic',
          chartLabel: 'Aquatic',
          chartLegendValues: 5,
          chartCSSColor: {
            0: '#E9ECEF',
            1: '#cde1e8',
            2: '#82bcd1',
            3: '#5ea5bb',
            4: '#007e91',
            5: '#005a62',
          },
          chartDriver: true,
          chartSummary: false,
          chartOrder: 1,
          chartInputName: 'fishandwildlife',
          ChartInputLabel: 'Fish and Wildlife Inputs',
          chartCSSSelector: 'aquatic',
          chartMaxValue: 6,
          chartMinValue: 0,
          chartScale: 0,
          chartScaleGroups: 1,
          chartNoDataOverRide: 1,
          url: "https://tiles.resilientcoasts.org/AquaticIndexTiles/{z}/{x}/{y}.png",
          attribution: "NFWF 2020",
          format: "image/png",
          tileSize: 256,
          transparent: true,
          opacity: 0.75,
          zIndex: 9000,
          crs: L.CRS.EPSG3857,
          maxNativeZoom: 12,
          tms: false,
          legend: "aquatic",
          description: "An index of priority aquatic species and their habitats, ranked by HUC-10 watershed. A high value represents watersheds where the most priority species and their habitats are present.",
          source: 'regional',
          region: 'continental_us'
        },
        {
          id: "CONUS_TerrestrialTMS",
          layer: "Terrestrial TMS",
          label: "Terrestrial Index",
          apikey: 'terrestrial',
          hubsapikey: 'terrestrial',
          chartLabel: 'Terrestrial',
          chartLegendValues: 5,
          chartCSSColor: {
            0: '#E9ECEF',
            1: '#ffe9c4',
            2: '#dfc878',
            3: '#79684e',
            4: '#385b23',
            5: '#004900',
          },
          chartDriver: true,
          chartSummary: false,
          chartOrder: 2,
          chartInputName: 'fishandwildlife',
          ChartInputLabel: 'Fish and Wildlife Inputs',
          chartCSSSelector: 'terrestrial',
          chartMaxValue: 6,
          chartMinValue: 0,
          chartScale: 0,
          chartScaleGroups: 1,
          chartNoDataOverRide: 1,
          url: "https://tiles.resilientcoasts.org/TerrestrialIndexTiles/{z}/{x}/{y}.png",
          attribution: "NFWF 2020",
          format: "image/png",
          tileSize: 256,
          transparent: true,
          opacity: 0.75,
          zIndex: 9000,
          crs: L.CRS.EPSG3857,
          maxNativeZoom: 12,
          tms: false,
          legend: "terrestrial",
          description: "An index of priority terrestrial species and their habitats, ranked by HUC-10 watershed. This Index also includes Important Bird Areas, which transcend watershed boundaries. A high value represents areas where the most priority species, their habitats, and important bird areas are present.",
          source: 'regional',
          region: 'continental_us'
        },
        {
          id: "CONUS_PopDensityTMS",
          layer: "Population Density TMS",
          label: "Population Density",
          apikey: 'pop_density',
          hubsapikey: 'pop_density',
          chartDriver: true,
          chartSummary: false,
          chartOrder: 1,
          chartInputName: 'asset',
          ChartInputLabel: 'Comunity Assets Inputs',
          chartLabel: 'Population Density',
          chartLegendValues: 5,
          chartCSSColor: {
            0: '#E9ECEF',
            1: '#dfc878',
            2: '#efc133',
            3: '#9eac37',
            4: '#2c8d7a',
            5: '#385a4c',
          },
          chartCSSSelector: 'population-density',
          chartMaxValue: 6,
          chartMinValue: 0,
          chartScale: 0,
          chartScaleGroups: 1,
          chartNoDataOverRide: 1,
          url: "https://tiles.resilientcoasts.org/PopDensityIndexTiles/{z}/{x}/{y}.png",
          attribution: "NFWF 2020",
          format: "image/png",
          tileSize: 256,
          transparent: true,
          opacity: 0.75,
          zIndex: 9000,
          crs: L.CRS.EPSG3857,
          maxNativeZoom: 12,
          tms: false,
          legend: "popdensity",
          description: "A ranking of population density by census blocks based on the 2016 American Community Survey. Areas are ranked from low to high using the ratio of people per square kilometer.",
          source: 'regional',
          region: 'continental_us'
        },
        {
          id: "CONUS_SocVulnTMS",
          layer: "Social Vulnerability TMS",
          label: "Social Vulnerability",
          apikey: 'social_vuln',
          hubsapikey: 'social_vuln',
          chartLabel: 'Social Vulnerability',
          chartLegendValues: 3,
          chartCSSColor: {
            0: '#E9ECEF',
            1: '#abd2fa',
            2: '#7692ff',
            3: '#3a1459',
          },
          chartDriver: true,
          chartSummary: false,
          chartOrder: 2,
          chartInputName: 'asset',
          ChartInputLabel: 'Comunity Assets Inputs',
          chartCSSSelector: 'social-vulnerability',
          chartMaxValue: 3,
          chartMinValue: 0,
          chartScale: 0,
          chartScaleGroups: 1,
          chartNoDataOverRide: 1,
          url: "https://tiles.resilientcoasts.org/SocVulnIndexTiles/{z}/{x}/{y}.png",
          attribution: "NFWF 2020",
          format: "image/png",
          tileSize: 256,
          transparent: true,
          opacity: 0.75,
          zIndex: 9000,
          crs: L.CRS.EPSG3857,
          maxNativeZoom: 12,
          tms: false,
          legend: "socvuln",
          description: "Communities that are socially vulnerable using the Demographic Index in EPA’s EJSCREEN dataset. Census blocks above the 80th percentile are ranked from low to high, depicting areas of lower median incomes and minority populations.",
          source: 'regional',
          region: 'continental_us'
        },
        {
          id: "CONUS_CriticalFacilitiesTMS",
          layer: "Critical Facilities TMS",
          label: "Critical Facilities",
          apikey: 'crit_facilities',
          hubsapikey: 'crit_facilities',
          chartLabel: 'Critical Facilities',
          chartLegendValues: 5,
          chartCSSColor: {
            0: '#E9ECEF',
            1: '#0084a8',
            2: '#0084a8',
            3: '#0084a8',
            4: '#0084a8',
            5: '#0084a8', // 5
          },
          chartDriver: true,
          chartSummary: false,
          chartOrder: 3,
          chartInputName: 'asset',
          ChartInputLabel: 'Comunity Assets Inputs',
          chartCSSSelector: 'critical-facilities',
          chartMaxValue: 6,
          chartMinValue: 0,
          chartScale: 0,
          chartScaleGroups: 1,
          chartNoDataOverRide: 1,
          url: "https://tiles.resilientcoasts.org/CriticalFacilitiesIndexTiles/{z}/{x}/{y}.png",
          attribution: "NFWF 2020",
          format: "image/png",
          tileSize: 256,
          transparent: true,
          opacity: 0.75,
          zIndex: 9000,
          crs: L.CRS.EPSG3857,
          maxNativeZoom: 12,
          tms: false,
          legend: "critfac",
          description: "Facilities such as schools, hospitals, and police and fire stations that are important to recovery efforts when a community is faced with a flood-related event. All facilities are given the same presence rank.",
          source: 'regional',
          region: 'continental_us'
        },
        {
          id: "CONUS_CriticalInfrastructureTMS",
          layer: "Critical Infrastructure TMS",
          label: "Critical Infrastructure",
          apikey: 'crit_infra',
          hubsapikey: 'crit_infra',
          chartLabel: 'Critical Infrastructure',
          chartLegendValues: 6,
          chartCSSColor: {
            0: '#E9ECEF',
            1: '#ccd1d2',
            2: '#355c59',
            3: '#e8b16d',
            4: '#b15a3c',
            5: '#ad3541',
            6: '#7b1733',
          },
          chartDriver: true,
          chartSummary: false,
          chartOrder: 4,
          chartInputName: 'asset',
          ChartInputLabel: 'Comunity Assets Inputs',
          chartCSSSelector: 'critical-infrastructure',
          chartMaxValue: 2,
          chartMinValue: 0,
          chartScale: 0,
          chartScaleGroups: 1,
          chartNoDataOverRide: 1,
          url: "https://tiles.resilientcoasts.org/CriticalInfrastructureIndexTiles/{z}/{x}/{y}.png",
          attribution: "NFWF 2020",
          format: "image/png",
          tileSize: 256,
          transparent: true,
          opacity: 0.75,
          zIndex: 9000,
          crs: L.CRS.EPSG3857,
          maxNativeZoom: 12,
          tms: false,
          legend: "critinfra",
          description: "Infrastructure in and around communities that are integral to a community’s ability to recover from a flood event, including primary highways, power plants, and rail lines, among others. High values suggest areas where multiple infrastructure overlap.",
          source: 'regional',
          region: 'continental_us'
        },
        {
          id: "CONUS_DrainageTMS",
          layer: "Drainage TMS",
          label: "Impermeable Soils",
          apikey: 'drainage',
          hubsapikey: 'drainage',
          chartLabel: 'Impermeable Soils',
          chartLegendValues: 5,
          chartCSSColor: {
            0: '#E9ECEF',
            1: '#447604',
            2: '#77D66F',
            3: '#dce9f2',
            4: '#755b69',
            5: '#553555',
          },
          chartDriver: true,
          chartSummary: false,
          chartOrder: 1,
          chartInputName: 'threat',
          ChartInputLabel: 'Threats Inputs',
          chartCSSSelector: 'drainage',
          chartMaxValue: 6,
          chartMinValue: 0,
          chartScale: 0,
          chartScaleGroups: 1,
          chartNoDataOverRide: 1,
          url: "https://tiles.resilientcoasts.org/DraingeIndexTiles/{z}/{x}/{y}.png",
          attribution: "NFWF 2020",
          format: "image/png",
          tileSize: 256,
          transparent: true,
          opacity: 0.75,
          zIndex: 9000,
          crs: L.CRS.EPSG3857,
          maxNativeZoom: 12,
          tms: false,
          legend: "drainage",
          description: "Those areas with poor water drainage potential, including both less-porous soils and areas with high-intensity development. High values suggest that areas contain soils with poor drainage potential and/or a prevalence of developed, impervious surfaces that may pool during flooding or heavy precipitation events.",
          source: 'regional',
          region: 'continental_us'
        },
        {
          id: "CONUS_ErosionTMS",
          layer: "Erosion TMS",
          label: "Soil Erodibility",
          apikey: 'erosion',
          hubsapikey: 'erosion',
          chartLabel: 'Soil Erodibility',
          chartLegendValues: 5,
          chartCSSColor: {
            0: '#E9ECEF',
            1: '#feeba2',
            2: '#febb47',
            3: '#f07818',
            4: '#b84203',
            5: '#662506',
          },
          chartDriver: true,
          chartSummary: false,
          chartOrder: 2,
          chartInputName: 'threat',
          ChartInputLabel: 'Threats Inputs',
          chartCSSSelector: 'erosion',
          chartMaxValue: 6,
          chartMinValue: 0,
          chartScale: 0,
          chartScaleGroups: 1,
          chartNoDataOverRide: 1,
          url: "https://tiles.resilientcoasts.org/ErosionIndexTiles/{z}/{x}/{y}.png",
          attribution: "NFWF 2020",
          format: "image/png",
          tileSize: 256,
          transparent: true,
          opacity: 0.75,
          zIndex: 9000,
          crs: L.CRS.EPSG3857,
          maxNativeZoom: 12,
          tms: false,
          legend: "erosion",
          description: "Those areas that contain soil characteristics that have a high susceptibility of soil particle detachment by water. This may include areas that have high silt content or migratory systems such as beaches and dunes. High values suggest that areas carry an increased potential for erosion due to flooding or heavy precipitation events.",
          source: 'regional',
          region: 'continental_us'
        },
        {
          id: "CONUS_SLRTMS",
          layer: "Sea Level Rise TMS",
          label: "Sea Level Rise",
          apikey: 'sea_level_rise',
          hubsapikey: 'sea_level_rise',
          chartLabel: 'Sea Level Rise',
          chartLegendValues: 5,
          chartCSSColor: {
            0: '#E9ECEF',
            1: '#dbd8ea',
            2: '#99b9d9',
            3: '#4095c3',
            4: '#027976',
            5: '#014636',
          },
          chartDriver: true,
          chartSummary: false,
          chartOrder: 3,
          chartInputName: 'threat',
          ChartInputLabel: 'Threats Inputs',
          chartCSSSelector: 'sea-level-rise',
          chartMaxValue: 6,
          chartMinValue: 0,
          chartScale: 0,
          chartScaleGroups: 1,
          chartNoDataOverRide: 1,
          url: "https://tiles.resilientcoasts.org/SLRIndexTiles/{z}/{x}/{y}.png",
          attribution: "NFWF 2020",
          format: "image/png",
          tileSize: 256,
          transparent: true,
          opacity: 0.75,
          zIndex: 9000,
          crs: L.CRS.EPSG3857,
          maxNativeZoom: 12,
          tms: false,
          legend: "slr",
          description: "NOAA’s sea level rise scenarios ranked from low to high, with low being a 5-foot scenario and high being a 1-foot scenario. These ranks are used to suggest the more imminent threat of a 1-foot rise in sea level versus a 5-foot rise that may eventually occur.",
          source: 'regional',
          region: 'continental_us'
        },
        {
          id: "CONUS_StormSurgeTMS",
          layer: "Storm Surge TMS",
          label: "Storm Surge",
          apikey: 'storm_surge',
          hubsapikey: 'stormsurge',
          chartLabel: 'Storm Surge',
          chartLegendValues: 5,
          chartCSSColor: {
            0: '#E9ECEF',
            1: '#d6efb3',
            2: '#73c8bd',
            3: '#2498c1',
            4: '#234da0',
            5: '#081d58',
          },
          chartDriver: true,
          chartSummary: false,
          chartOrder: 4,
          chartInputName: 'threat',
          ChartInputLabel: 'Threats Inputs',
          chartCSSSelector: 'storm-surge',
          chartMaxValue: 6,
          chartMinValue: 0,
          chartScale: 0,
          chartScaleGroups: 1,
          chartNoDataOverRide: 1,
          url: "https://tiles.resilientcoasts.org/StormSurgeIndexTiles/{z}/{x}/{y}.png",
          attribution: "NFWF 2020",
          format: "image/png",
          tileSize: 256,
          transparent: true,
          opacity: 0.75,
          zIndex: 9000,
          crs: L.CRS.EPSG3857,
          maxNativeZoom: 12,
          tms: false,
          legend: "stormsurge",
          description: "Based on the impacts from modeled hurricane storm categories, storm surge is ranked from low to high, with low being a 5-foot surge and high being a 1-foot surge. As a 1-foot surge is more likely to occur than a 5-foot surge, areas within the 1-foot designation are ranked with higher values.",
          source: 'regional',
          region: 'continental_us'
        },
        {
          id: "CONUS_GeoStressTMS",
          layer: "Geo Stressors TMS",
          label: "Geological Stressors",
          apikey: 'geostress',
          hubsapikey: 'geostress',
          chartLabel: 'Geological Stressors',
          chartLegendValues: 3,
          chartCSSColor: {
            0: '#E9ECEF',
            1: '#fbacb9',
            2: '#cd238f',
            3: '#49006a',
          },
          chartDriver: true,
          chartSummary: false,
          chartOrder: 4,
          chartInputName: 'threat',
          ChartInputLabel: 'Threats Inputs',
          chartCSSSelector: 'geostress',
          chartMaxValue: 3,
          chartMinValue: 0,
          chartScale: 0,
          chartScaleGroups: 1,
          chartNoDataOverRide: 1,
          url: "https://tiles.resilientcoasts.org/GeoStressIndexTiles/{z}/{x}/{y}.png",
          attribution: "NFWF 2020",
          format: "image/png",
          tileSize: 256,
          transparent: true,
          opacity: 0.75,
          zIndex: 9000,
          crs: L.CRS.EPSG3857,
          maxNativeZoom: 12,
          tms: false,
          legend: "geostress",
          description: "The geologic conditions of the landscape that can exacerbate the level of threat represented from other inputs. Conditions that are highlighted in this input include both landslide susceptibility and subsidence.",
          source: 'regional',
          region: 'continental_us'
        },
        {
          id: "CONUS_SlopeTMS",
          layer: "Slope TMS",
          label: "Areas of Low Slope",
          apikey: 'slope',
          hubsapikey: 'slope',
          chartLabel: 'Areas of Low Slope',
          chartLegendValues: 5,
          chartCSSColor: {
            0: '#E9ECEF',
            1: '#d3eecd',
            2: '#98d594',
            3: '#4bb062',
            4: '#157f3b',
            5: '#00441b',
          },
          chartDriver: true,
          chartSummary: false,
          chartOrder: 5,
          chartInputName: 'threat',
          ChartInputLabel: 'Threats Inputs',
          chartCSSSelector: 'slope',
          chartMaxValue: 6,
          chartMinValue: 0,
          chartScale: 0,
          chartScaleGroups: 1,
          chartNoDataOverRide: 1,
          url: "https://tiles.resilientcoasts.org/SlopeIndexTiles/{z}/{x}/{y}.png",
          attribution: "NFWF 2020",
          format: "image/png",
          tileSize: 256,
          transparent: true,
          opacity: 0.75,
          zIndex: 9000,
          crs: L.CRS.EPSG3857,
          maxNativeZoom: 12,
          tms: false,
          legend: "slope",
          description: "The percent rise of the elevation of the landscape, given values from low to high. High values indicate those areas that are very low lying and more likely to retain water and flood.",
          source: 'regional',
          region: 'continental_us'
        },
        {
          id: "CONUS_FloodProneAreasTMS",
          layer: "Flood Prone Areas TMS",
          label: "Flood-Prone Areas",
          apikey: 'floodprone_areas',
          hubsapikey: 'floodprone_areas',
          chartLabel: 'Flood Prone Areas',
          chartLegendValues: 5,
          chartCSSColor: {
            0: '#E9ECEF',
            1: '#e2e2ef',
            2: '#b6b6d8',
            3: '#8683bd',
            4: '#61409b',
            5: '#3f007d',
          },
          chartDriver: true,
          chartSummary: false,
          chartOrder: 6,
          chartInputName: 'threat',
          ChartInputLabel: 'Threats Inputs',
          chartCSSSelector: 'floodprone-areas',
          chartMaxValue: 6,
          chartMinValue: 0,
          chartScale: 0,
          chartScaleGroups: 1,
          chartNoDataOverRide: 1,
          url: "https://tiles.resilientcoasts.org/FloodProneAreasIndexTiles/{z}/{x}/{y}.png",
          attribution: "NFWF 2020",
          format: "image/png",
          tileSize: 256,
          transparent: true,
          opacity: 0.75,
          zIndex: 9000,
          crs: L.CRS.EPSG3857,
          maxNativeZoom: 12,
          tms: false,
          legend: "floodprone",
          description: "Areas considered by FEMA to be in the 100- and 500-year flood zones, as well as the floodway. Frequently and occasionally flooded soil designations are used to identify areas outside of FEMA coverage. Highest values suggest areas directly in the floodway, whereas low values suggest occasionally flooded soils outside of the floodplain.",
          source: 'regional',
          region: 'continental_us'
        },
      ]
  
}