import regionGreatLakesImage from '../../assets/images/zoomregion-great_lakes-v2.png';

export const greatLakesConfig = {
  label: 'U.S. Great Lakes',
  image: regionGreatLakesImage,
  regionName: 'great_lakes',
  reportEnglish: {
    fileLink: 'https://www.nfwf.org/sites/default/files/2023-06/us-great-lakes-coastal-resilience-assessment-2023.pdf',
    name: 'U.S. Great Lakes Assessment'
  },
  reportNative: {
    fileLink: null,
    name: null
  },
  dataDownload: {
    fileSize: '610 MB',
    fileLink: 'https://nfwf-tool.s3.amazonaws.com/nfwf_download_data/Great_Lakes_Data_Download_20230605.zip',
    name: 'U.S. Great Lakes Data Download'
  },
  mapProperties: {
    label: 'Great_Lakes',
    center: [45.32, -84.47],
    extent: [-92.03, 47.28, -76.52, 42.19],
    zoom: 6
  },
  attribution: 'NFWF 2022',
  hubsFeatureServer: 'https://services1.arcgis.com/PwLrOgCfU0cYShcG/ArcGIS/rest/services/gl_hubs_cores_052323_CREST_3857_sean_2/FeatureServer/0',
  hubsHexServer: 'https://services1.arcgis.com/PwLrOgCfU0cYShcG/arcgis/rest/services/gl_hubs_hex_052323_CREST_3857/FeatureServer/0',
  rankProperty: 'rank_val', // need this in config because the rank property is different for all of the regions
  chartInputs: [
    {
      chartInputName: 'summary',
      ChartInputLabel: 'Summary'
    },
    {
      chartInputName: 'asset',
      ChartInputLabel: 'Community Assets Inputs'
    },
    {
      chartInputName: 'threat',
      ChartInputLabel: 'Threats Inputs'
    },
    {
      chartInputName: 'fishandwildlife',
      ChartInputLabel: 'Fish and Wildlife Inputs'
    },
    {
      chartInputName: 'additional',
      ChartInputLabel: 'Additional Overlays'
    }
  ],
  layerList: [
    {
      id: 'GL_HubsTMS',
      layer: 'Hubs TMS',
      label: 'Resilience Hubs',
      chartLabel: 'Resilience Hubs',
      chartCSSColor: {
        0: '#E9ECEF',
        1: '#ffc500',
        2: '#f9b500',
        3: '#f3a400',
        4: '#ed9400',
        5: '#e78300',
        6: '#e07000',
        7: '#d95e00',
        8: '#d14c00',
        9: '#ca3600',
        10: '#c21500'
      },
      chartInputName: 'summary',
      ChartInputLabel: 'Summary',
      ChartInputSubHeading: 'Resilience Hubs',
      chartCSSSelector: 'hubs',
      url: 'https://tiles.resilientcoasts.org/GL_HubsIndexTiles/{z}/{x}/{y}.png',
      attribution: 'NFWF 2022',
      opacity: 0.75,
      maxNativeZoom: 14,
      description: 'Resilience Hub Cores represent contiguous, unfragmented habitat cores proximate to human community assets ranked by combining Community Exposure and Fish and Wildlife Index values with other key inputs. Resilience Hub Cores provide a coarse-scale view of Resilience Hubs, where higher values represent areas with greater potential for dual community flood protection and wildlife benefits. See the U.S. U.S. Great Lakes Assessment report for details.',
      region: 'great_lakes'
    },
    {
      id: 'GL_HubsHexTMS',
      layer: 'Hubs Hex TMS',
      label: 'Resilience Hub Grid',
      chartLabel: 'Resilience Hub Grid',
      chartInputName: 'summary',
      ChartInputLabel: 'Summary',
      ChartInputSubHeading: 'Resilience Hubs',
      chartCSSColor: {
        0: '#E9ECEF',
        1: '#ffc500',
        2: '#f9b500',
        3: '#f3a400',
        4: '#ed9400',
        5: '#e78300',
        6: '#e07000',
        7: '#d95e00',
        8: '#d14c00',
        9: '#ca3600',
        10: '#c21500'
      },
      url: 'https://tiles.resilientcoasts.org/GL_HubsHexIndexTiles/{z}/{x}/{y}.png',
      attribution: 'NFWF 2022',
      opacity: 0.75,
      maxNativeZoom: 14,
      description: 'The Resilience Hub Grid applies a 10-acre hexagonal grid to show variation within habitat cores, ranking each hexagon by combining Community Exposure and Fish and Wildlife Index values with other key inputs. The Resilience Hub Grid provides a fine-scale view of Resilience Hubs, where higher values represent areas with greater potential for dual community flood protection and wildlife benefits. See the U.S. U.S. Great Lakes Assessment report for details.',
      region: 'great_lakes'
    },
    {
      id: 'GL_ExposureTMS',
      layer: 'Exposure TMS',
      label: 'Community Exposure Index',
      chartLabel: 'Community Exposure',
      chartCSSColor: {
        0: '#E9ECEF',
        1: '#FFFFE5',
        2: '#FFF8C1',
        3: '#FEE79B',
        4: '#FECE65',
        5: '#FEAC3A',
        6: '#F68720',
        7: '#E1640E',
        8: '#C14702',
        9: '#933204',
        10: '#662506'
      },
      chartInputName: 'summary',
      ChartInputLabel: 'Summary',
      ChartInputSubHeading: 'Community Exposure Index',
      chartCSSSelector: 'exposure',
      url: 'https://tiles.resilientcoasts.org/GL_ExposureIndexTiles/{z}/{x}/{y}.png',
      attribution: 'NFWF 2022',
      format: 'image/png',
      opacity: 0.75,
      maxNativeZoom: 14,

      description: 'The product of the Community Asset Index and Threat Index, the Community Exposure Index identifies areas where human community assets are potentially exposed to numerous flood-related threats. Color ramp varies from other regions but displays similar information. See the U.S. U.S. Great Lakes Assessment report for details.',
      region: 'great_lakes'
    },
    {
      id: 'GL_AssetsTMS',
      layer: 'Assets TMS',
      label: 'Community Asset Index',
      chartLabel: 'Community Asset',
      chartCSSColor: {
        0: '#E9ECEF',
        1: '#b6edf0',
        2: '#98d2ed',
        3: '#7cbbeb',
        4: '#5ca3e6',
        5: '#368de3',
        6: '#2176d9',
        7: '#2259c7',
        8: '#1d3eb5',
        9: '#1727a3',
        10: '#090991'
      },
      chartInputName: 'summary',
      ChartInputLabel: 'Summary',
      ChartInputSubHeading: 'Community Asset and Threat Indices',
      chartCSSSelector: 'asset',
      url: 'https://tiles.resilientcoasts.org/GL_AssetsIndexTiles/{z}/{x}/{y}.png',
      attribution: 'NFWF 2022',
      format: 'image/png',
      opacity: 0.75,
      maxNativeZoom: 14,
      description: 'Index of human community assets that are important to help a community respond to and recover from a flooding event. High values represent areas with dense concentration of critical facilities, infrastructure, and population and social vulnerability. See the U.S. U.S. Great Lakes Assessment report for details.',
      region: 'great_lakes'
    },
    {
      id: 'GL_ThreatsTMS',
      layer: 'Threats TMS',
      label: 'Threat Index',
      chartLabel: 'Threat',
      chartCSSColor: {
        0: '#E9ECEF',
        1: '#ffebd6',
        2: '#f7d7bc',
        3: '#f0c0a1',
        4: '#eba988',
        5: '#e3906f',
        6: '#de775b',
        7: '#d65d45',
        8: '#d14030',
        9: '#c9251c',
        10: '#c40a0a'
      },
      chartInputName: 'summary',
      ChartInputLabel: 'Summary',
      ChartInputSubHeading: 'Community Asset and Threat Indices',
      chartCSSSelector: 'threat',
      url: 'https://tiles.resilientcoasts.org/GL_ThreatsIndexTiles/{z}/{x}/{y}.png',
      attribution: 'NFWF 2022',
      format: 'image/png',
      opacity: 0.75,
      maxNativeZoom: 14,
      description: 'Index of flood-related datasets, including high lake levels and landscape characteristics that exacerbate flood potential. High values represent areas with multiple flood-related threat inputs. See the U.S. U.S. Great Lakes Assessment report for details.',
      region: 'great_lakes'
    },
    {
      id: 'GL_FishAndWildlifeTMS',
      layer: 'FishAndWildlife TMS',
      label: 'Fish and Wildlife Index',
      chartLabel: 'Fish and Wildlife',
      chartCSSColor: {
        0: '#E9ECEF',
        1: '#EEF8F3',
        2: '#EDD0E0',
        3: '#E9BBCB',
        4: '#E3A6B7',
        5: '#DB90A6',
        6: '#D27C99',
        7: '#C6678F',
        8: '#B7528A',
        9: '#A33F8F',
        10: '#7E33A8'
      },
      chartInputName: 'summary',
      ChartInputLabel: 'Summary',
      ChartInputSubHeading: 'Fish and Wildlife',
      chartCSSSelector: 'wildlife',
      url: 'https://tiles.resilientcoasts.org/GL_CombinedWildlifeIndexTiles/{z}/{x}/{y}.png',
      attribution: 'NFWF 2022',
      format: 'image/png',
      opacity: 0.75,
      maxNativeZoom: 14,
      description: 'The sum of the Terrestrial Index, Aquatic Index, and Protected and Managed Areas for Biodiversity, the Fish and Wildlife Index identifies habitat and protected areas important for terrestrial and aquatic species of conservation concern and/or off-reservation harvest regulations. Higher values represent areas important for numerous species of concern. See the U.S. U.S. Great Lakes Assessment report for details.',
      region: 'great_lakes'
    },
    {
      id: 'GL_AquaticTMS',
      layer: 'Aquatic TMS',
      label: 'Aquatic Index',
      chartLabel: 'Aquatic',
      chartCSSColor: {
        0: '#E9ECEF',
        1: '#FFF7FB',
        2: '#ECE7F2',
        3: '#D0D1E6',
        4: '#A6BDDB',
        5: '#74A9CF',
        6: '#3690C0',
        7: '#0570B0',
        8: '#045A8D',
        9: '#023858',
        10: '#01172C'
      },
      chartInputName: 'fishandwildlife',
      ChartInputLabel: 'Fish and Wildlife Inputs',
      chartCSSSelector: 'aquatic',
      url: 'https://tiles.resilientcoasts.org/GL_AquaticIndexTiles/{z}/{x}/{y}.png',
      attribution: 'NFWF 2022',
      format: 'image/png',
      opacity: 0.75,
      maxNativeZoom: 14,
      description: 'Index of habitat suitable for species of conservation concern and/or species with off-reservation harvest regulations that utilize riverine and lacustrine habitats. The Index also considers designated critical habitat, nearshore reefs and fish spawning locations, and U.S. Great Lakes Brook Trout Conservation Portfolio habitat patches, which served as a proxy for cool and cold-water habitat. High values represent areas important for numerous aquatic species of concern. See the U.S. U.S. Great Lakes Assessment report for details.',
      region: 'great_lakes'
    },
    {
      id: 'GL_TerrestrialTMS',
      layer: 'Terrestrial TMS',
      label: 'Terrestrial Index',

      chartLabel: 'Terrestrial',
      chartCSSColor: {
        0: '#E9ECEF',
        1: '#FFFFE5',
        2: '#F1E7B5',
        3: '#E3CE84',
        4: '#BAB065',
        5: '#888F4C',
        6: '#576F33',
        7: '#32591F',
        8: '#215415',
        9: '#114E0A',
        10: '#004900'
      },
      chartInputName: 'fishandwildlife',
      ChartInputLabel: 'Fish and Wildlife Inputs',
      chartCSSSelector: 'terrestrial',
      url: 'https://tiles.resilientcoasts.org/GL_TerrestrialIndexTiles/{z}/{x}/{y}.png',
      attribution: 'NFWF 2022',
      format: 'image/png',
      opacity: 0.75,
      maxNativeZoom: 14,
      description: 'Index of habitat suitable for species of conservation concern and/or species with off-reservation harvest regulations that utilize terrestrial habitats. The Index also considers designated critical habitat, Important Bird Areas, and Key Biodiversity Areas. High values represent areas important for numerous terrestrial species of concern. See the U.S. U.S. Great Lakes Assessment report for details.',
      region: 'great_lakes'
    },
    {
      id: 'GL_SocVulnTMS',
      layer: 'Social Vulnerability TMS',
      label: 'Social Vulnerability',
      chartLabel: 'Social Vulnerability',
      chartCSSColor: {
        0: '#E9ECEF',
        1: '#9EBBD7',
        2: '#7A8EF5',
        3: '#43309D',
        4: '#321699',
        5: '#270B59'
      },
      chartInputName: 'asset',
      ChartInputLabel: 'Community Assets Inputs',
      chartCSSSelector: 'social_vuln',
      url: 'https://tiles.resilientcoasts.org/GL_SocVulnIndexTiles/{z}/{x}/{y}.png',
      attribution: 'NFWF 2022',
      opacity: 0.75,
      maxNativeZoom: 14,
      description: 'Identifies census blocks that are socially vulnerable using the Demographic Index in EPA’s EJSCREEN data. Census blocks above the 50th percentile nationally are ranked from low to high, which indicates census blocks with low income and minority populations. See the U.S. U.S. Great Lakes Assessment report for details.',
      region: 'great_lakes'
    },
    {
      id: 'GL_PopDensityTMS',
      layer: 'Population Density TMS',
      label: 'Population Density',
      chartLabel: 'Population Density',
      chartCSSColor: {
        0: '#E9ECEF',
        1: '#fff6d0',
        2: '#efc133',
        3: '#9eac37',
        4: '#2c8d7a',
        5: '#385a4c'
      },
      chartInputName: 'asset',
      ChartInputLabel: 'Community Assets Inputs',
      chartCSSSelector: 'pop_density',
      url: 'https://tiles.resilientcoasts.org/GL_PopDensityIndexTiles/{z}/{x}/{y}.png',
      attribution: 'NFWF 2020',
      format: 'image/png',
      opacity: 0.75,
      maxNativeZoom: 14,
      description: 'A ranking of population density by census blocks based on the 2020 Decennial Census. Areas are ranked from low to high using the ratio of people per square kilometer relative to the most densely populated census block in the study area. See the U.S. U.S. Great Lakes Assessment report for details.',
      region: 'great_lakes'
    },
    {
      id: 'GL_CriticalFacilitiesTMS',
      layer: 'Critical Facilities TMS',
      label: 'Critical Facilities',

      chartLabel: 'Critical Facilities',
      chartCSSColor: {
        0: '#E9ECEF',
        1: '#0084A8', // 5
        2: '#0084A8', // 5
        3: '#0084A8', // 5
        4: '#0084A8', // 5
        5: '#0084A8' // 5
      },
      chartInputName: 'asset',
      ChartInputLabel: 'Community Assets Inputs',
      chartCSSSelector: 'crit_facilities',
      url: 'https://tiles.resilientcoasts.org/GL_CriticalFacilitiesIndexTiles/{z}/{x}/{y}.png',
      attribution: 'NFWF 2022',
      format: 'image/png',
      opacity: 0.75,
      maxNativeZoom: 14,
      description: 'Facilities that provide important recovery and operational support during and following flood events such as schools, emergency response and law enforcement facilities, health and medical facilities, and government and military buildings. All critical facilities are given the same rank based on presence. See the U.S. U.S. Great Lakes Assessment report for details.',
      region: 'great_lakes'
    },
    {
      id: 'GL_CommunityInfrastructureTMS',
      layer: 'Critical Infrastructure TMS',
      label: 'Critical Infrastructure',

      chartLabel: 'Critical Infrastructure',
      chartCSSColor: {
        0: '#E9ECEF',
        1: '#A82B41', // 5
        2: '#A82B41', // 5
        3: '#A82B41', // 5
        4: '#A82B41', // 5
        5: '#A82B41' // 5
      },
      chartInputName: 'asset',
      ChartInputLabel: 'Community Assets Inputs',
      chartCSSSelector: 'crit_infra',
      url: 'https://tiles.resilientcoasts.org/GL_CommunityInfrastructurIndexTiles/{z}/{x}/{y}.png',
      attribution: 'NFWF 2022',
      format: 'image/png',
      opacity: 0.75,
      maxNativeZoom: 14,
      description: 'Infrastructure integral to a community’s ability to mitigate damages and recover from a flood event, including transportation, waterways, water treatment, communications, energy, and hazardous site infrastructure. All critical infrastructure is given the same rank based on presence. High values indicate areas where one or more infrastructure types are nearby or overlap. See the U.S. U.S. Great Lakes Assessment report for details.',
      region: 'great_lakes'
    },
    {
      id: 'GL_ErosionTMS',
      layer: 'Erosion TMS',
      label: 'Soil Erodibility',
      chartLabel: 'Soil Erodibility',
      chartCSSColor: {
        0: '#E9ECEF',
        1: '#FEEBA2',
        2: '#FEBB47',
        3: '#F07818',
        4: '#B84203',
        5: '#662506'
      },
      chartInputName: 'threat',
      ChartInputLabel: 'Threats Inputs',
      chartCSSSelector: 'erosion',
      url: 'https://tiles.resilientcoasts.org/GL_ErosionIndexTiles/{z}/{x}/{y}.png',
      attribution: 'NFWF 2022',
      format: 'image/png',
      opacity: 0.75,
      maxNativeZoom: 14,
      description: 'Soils identified as having a high probability of erodibility including coastal bluffs, beaches, and dunes. High values suggest that the area contains soils with a high erodibility factor. See the U.S. U.S. Great Lakes Assessment report for details.',
      region: 'great_lakes'
    },
    {
      id: 'GL_FloodProneAreasTMS',
      layer: 'Flood Prone Areas TMS',
      label: 'Flood-prone Areas',

      chartLabel: 'Flood-prone Areas',
      chartCSSColor: {
        0: '#E9ECEF',
        1: '#E2E2EF',
        2: '#B6B6D8',
        3: '#8683BD',
        4: '#61409B',
        5: '#3F007D'
      },
      chartInputName: 'threat',
      ChartInputLabel: 'Threats Inputs',
      chartCSSSelector: 'floodprone_areas',
      url: 'https://tiles.resilientcoasts.org/GL_FloodProneAreasIndexTiles/{z}/{x}/{y}.png',
      attribution: 'NFWF 2022',
      format: 'image/png',
      opacity: 0.75,
      maxNativeZoom: 14,
      description: 'Areas classified by FEMA to be in the 100-year flood zone, 500-year flood zones, or a floodway. Frequently and occasionally flooded soil designations are used to identify additional areas. A high value indicates the floodplain, while a low value indicates occasionally flooded soils outside of the floodplain. See the U.S. U.S. Great Lakes Assessment report for details.',
      region: 'great_lakes'
    },
    {
      id: 'GL_SlopeTMS',
      layer: 'Slope TMS',
      label: 'Areas of Low Slope',
      chartLabel: 'Areas of Low Slope',
      chartCSSColor: {
        0: '#E9ECEF',
        1: '#d3eecd',
        2: '#98d594',
        3: '#4bb062',
        4: '#157f3b',
        5: '#00441b'
      },
      chartInputName: 'threat',
      ChartInputLabel: 'Threats Inputs',
      chartCSSSelector: 'slope',
      url: 'https://tiles.resilientcoasts.org/GL_SlopeIndexTiles/{z}/{x}/{y}.png',
      attribution: 'NFWF 2020',
      format: 'image/png',
      opacity: 0.75,
      maxNativeZoom: 14,
      description: 'The percent rise in elevation. High values indicate those areas that are very low lying and more likely to retain water and flood. See the U.S. U.S. Great Lakes Assessment report for details.',
      region: 'great_lakes'
    },
    {
      id: 'GL_DrainageTMS',
      layer: 'Drainage TMS',
      label: 'Impermeability',
      chartLabel: 'Impermeability',
      chartCSSColor: {
        0: '#E9ECEF',
        1: '#E9DD66',
        2: '#CBBA06',
        3: '#A19400',
        4: '#786D00',
        5: '#4D4700'
      },
      chartInputName: 'threat',
      ChartInputLabel: 'Threats Inputs',
      chartCSSSelector: 'impermeable',
      url: 'https://tiles.resilientcoasts.org/GL_DraingeIndexTiles/{z}/{x}/{y}.png',
      attribution: 'NFWF 2020',
      format: 'image/png',
      opacity: 0.75,
      maxNativeZoom: 14,
      description: 'Areas with poor drainage potential, including both soils and areas with low to high intensity development that do not readily drain and have runoff potential. A high value indicates areas that have soils with poor drainage potential and/or an intensity of developed impervious surfaces. A correction factor has been applied to account for poorly drained soils in row crop agricultural areas using tile drainage. See the U.S. U.S. Great Lakes Assessment report for details.',
      region: 'great_lakes'
    },
    {
      id: 'GL_MaxWaterLevelTMS',
      layer: 'MaxWaterLevel TMS',
      label: 'High Water Level',

      chartLabel: 'High Water Level',
      chartCSSColor: {
        0: '#E9ECEF',
        1: '#DBD8EA',
        2: '#99B9D9',
        3: '#4095C3',
        4: '#027976',
        5: '#014636'
      },
      chartInputName: 'threat',
      ChartInputLabel: 'Threats Inputs',
      chartCSSSelector: 'highwater',
      url: 'https://tiles.resilientcoasts.org/GL_MaxWaterLevelIndexTiles/{z}/{x}/{y}.png',
      attribution: 'NFWF 2020',
      format: 'image/png',
      opacity: 0.75,
      maxNativeZoom: 14,
      description: 'Used to identify high lake levels estimated from global satellite imagery. Data show the distribution of surface water from 1984-2020 and represent intra- and inter-annual variation based on observed lake level changes. High values indicate areas that are more likely to have experienced higher lake levels. See the U.S. U.S. Great Lakes Assessment report for details.',
      region: 'great_lakes'
    },
    {
      id: 'GL_VisualizationOverlay1TMS',
      layer: 'Visualization Overlay 1 TMS',
      label: 'American Indian/Alaska Native/Native Hawaiian (AIANNH) Areas',
      chartLabel: 'AIANNHA',
      chartCSSColor: {
        0: '#E9ECEF'
      },
      chartInputName: 'VisualizationOverlays',
      ChartInputLabel: 'Additional Overlays',
      url: 'https://tiles.resilientcoasts.org/GL_AIANNHAIndexTiles/{z}/{x}/{y}.png',
      attribution: 'NFWF 2020',
      format: 'image/png',
      opacity: 0.75,
      maxNativeZoom: 14,
      description: 'Boundaries of Federal American Indian Reservations, Off-Reservation Trust Lands (ORTL), State American Indian Reservations, Hawaiian Home Lands (HHL), Alaska Native Village Statistical Areas (ANVSA), Oklahoma Tribal Statistical Areas (OTSA), State Designated Tribal Statistical Areas (SDTSA), Tribal Designated Statistical Areas (TDSA), American Indian Joint-Use Areas (AIJUA), Joint-Use Oklahoma Tribal Statistical Areas.',
      region: 'great_lakes'
    },
    {
      id: 'GL_VisualizationOverlay2TMS',
      layer: 'Visualization Overlay2 TMS',
      label: 'Ceded Territory',
      chartLabel: 'Ceded Territory',
      chartCSSColor: {
        0: '#E9ECEF'
      },
      chartInputName: 'VisualizationOverlays',
      ChartInputLabel: 'Additional Overlays',
      url: 'https://tiles.resilientcoasts.org/GL_CededTerritoryIndexTiles/{z}/{x}/{y}.png',
      attribution: 'NFWF 2020',
      format: 'image/png',
      opacity: 1.0,
      maxNativeZoom: 14,
      description: 'U.S. Great Lakes Indian Fish and Wildlife Commission representation of the boundaries of the 1836, 1837, 1842 and 1854 treaty areas of the Ojibwe ceded territories in Michigan, Minnesota and Wisconsin.',
      region: 'great_lakes'
    },
    // DOD data un comment when ready also uncomment the layer int maplayers_list.html
    // {
    //   id: "GL_VisualizationOverlay3TMS",
    //   layer: "Visualization Overlay3 TMS",
    //   label: "Department of Defense Lands",
    //   chartLabel: 'Department of Defense Lands',
    //       //   chartCSSColor: {
    //     0: '#E9ECEF',
    //   },
    //   chartInputName: 'VisualizationOverlays',
    //   ChartInputLabel: 'Additional Overlays',
    //   chartCSSSelector: 'VisualizationOverlay3',
    //   url: "https://tiles.resilientcoasts.org/GL_USA_Department_of_Defense_LandsIndexTiles/{z}/{x}/{y}.png",
    //   attribution: "NFWF 2020",
    //   format: "image/png",
    //   opacity: 0.75,
    //   maxNativeZoom: 14,
    //   description: "Visualization Overlay Two, needs a description",
    //   region: 'great_lakes'
    // },
    {
      id: 'GL_VisualizationOverlay4TMS',
      layer: 'Visualization Overlay4 TMS',
      label: 'Fetch',
      chartLabel: 'Fetch',
      chartCSSColor: {
        0: '#E9ECEF'
      },
      chartInputName: 'VisualizationOverlays',
      ChartInputLabel: 'Additional Overlays',
      url: 'https://tiles.resilientcoasts.org/GL_FetchIndexTiles/{z}/{x}/{y}.png',
      attribution: 'NFWF 2020',
      format: 'image/png',
      opacity: 0.75,
      maxNativeZoom: 14,
      description: 'U.S. Great Lakes Aquatic Habitat Framework composite fetch data layer where wind fetch calculations were performed for each of the U.S. Great Lakes using wind data averaged from 2006-2014 during open-water months (April-Nov.). Wind fetches in this model were calculated as effective fetch at a 30 m grid cell resolution resulting from the directional frequency method where each grid cell is the distance to shore along each input direction weighted by the percent frequency that the wind blew from that direction and summed, resulting in a continuous layer ranked from low (1) to high (5) using a regional quantile distribution.',
      region: 'great_lakes'
    },
    {
      id: 'GL_VisualizationOverlay5TMS',
      layer: 'Visualization Overlay5 TMS',
      label: 'Lake Level Fluctuation Zone',
      chartLabel: 'Lake Level Fluctuation Zone',
      chartCSSColor: {
        0: '#E9ECEF'
      },
      chartInputName: 'VisualizationOverlays',
      ChartInputLabel: 'Additional Overlays',
      chartCSSSelector: 'VisualizationOverlay5',
      url: 'https://tiles.resilientcoasts.org/GL_LakeFluctuationZoneIndexTiles/{z}/{x}/{y}.png',
      attribution: 'NFWF 2020',
      format: 'image/png',
      opacity: 0.75,
      maxNativeZoom: 14,
      description: 'Shows the spatial and temporal distribution of where non-permanent surface water occurred between 1984 and 2020. The layer captures both the intra and inter-annual variability and changes known as surface water occurrence.',
      region: 'great_lakes'
    },
    {
      id: 'GL_landcover',
      layer: 'landcover',
      label: 'Landcover',
      chartLabel: 'Landcover',
      chartCSSColor: {
        11: '#5475A8',
        12: '#FFFFFF',
        21: '#E8D1D1',
        22: '#E29E8C',
        23: '#ff0000',
        24: '#B50000',
        31: '#D2CDC0',
        41: '#85C77E',
        42: '#38814E',
        43: '#D4E7B0',
        51: '#AF963C',
        52: '#DCCA8F',
        71: '#FDE9AA',
        72: '#D1D182',
        73: '#A3CC51',
        74: '#82BA9E',
        81: '#FBF65D',
        82: '#CA9146',
        90: '#C8E6F8',
        95: '#64B3D5'
      },
      chartInputName: 'landcover',
      ChartInputLabel: 'Additional Overlays',
      chartCSSSelector: 'landcover',
      url: 'https://tiles.resilientcoasts.org/GL_NLCDTiles/{z}/{x}/{y}.png',
      attribution: 'NFWF 2023',
      opacity: 0.75,
      maxNativeZoom: 13,
      description: 'Insert Landcover Description Here', // TODO: INSERT DESCRIPTION
      region: 'great_lakes'
    }
  ],
  zonalStatsKeys: [
    'aquatic',
    'asset',
    'crit_facilities',
    'wildlife',
    'crit_infra',
    'erosion',
    'exposure',
    'floodprone_areas',
    'highwater',
    'hubs',
    'impermeable',
    'pop_density',
    'slope',
    'social_vuln',
    'terrestrial',
    'threat',
    'wildlife',
    'landcover_open_water',
    'landcover_perennial_icesnow',
    'landcover_developed_open_space',
    'landcover_developed_low_intensity',
    'landcover_developed_medium_intensity',
    'landcover_developed_high_intensity',
    'landcover_barren_land',
    'landcover_deciduous_forest',
    'landcover_evergreen_forest',
    'landcover_mixed_forest',
    'landcover_dwarf_scrub',
    'landcover_shrub_scrub',
    'landcover_grassland_herbaceous',
    'landcover_sedge_herbaceous',
    'landcover_lichens',
    'landcover_moss',
    'landcover_pasture_hay-areas',
    'landcover_cultivated_crops',
    'landcover_woody_wetlands',
    'landcover_emergent_herbaceous_wetlands'
  ],
  statesList: [
    'Illinois', 'Indiana', 'Michigan', 'Minnesota', 'New York', 'Ohio', 'Pennsylvania', 'Wisconsin'
  ],
  countiesList: [
    'Adams County, IN', 'Adams County, WI', 'Aitkin County, MN', 'Alcona County, MI', 'Alger County, MI',
    'Allegan County, MI', 'Allegany County, NY', 'Allen County, IN', 'Allen County, OH', 'Alpena County, MI',
    'Antrim County, MI', 'Arenac County, MI', 'Ashland County, OH', 'Ashland County, WI',
    'Ashtabula County, OH', 'Auglaize County, OH', 'Baraga County, MI', 'Barry County, MI', 'Bay County, MI',
    'Bayfield County, WI', 'Benzie County, MI', 'Berrien County, MI', 'Branch County, MI', 'Brown County, WI',
    'Calhoun County, MI', 'Calumet County, WI', 'Carlton County, MN', 'Cass County, MI',
    'Cattaraugus County, NY', 'Cayuga County, NY', 'Charlevoix County, MI', 'Chautauqua County, NY',
    'Cheboygan County, MI', 'Chemung County, NY', 'Chippewa County, MI', 'Clare County, MI', 'Clinton County, MI',
    'Columbia County, WI', 'Cook County, IL', 'Cook County, MN', 'Cortland County, NY',
    'Crawford County, MI', 'Crawford County, OH', 'Crawford County, PA', 'Cuyahoga County, OH', 'DeKalb County, IN',
    'Defiance County, OH', 'Delta County, MI', 'Dickinson County, MI', 'Dodge County, WI',
    'Door County, WI', 'Douglas County, WI', 'DuPage County, IL', 'Eaton County, MI', 'Elkhart County, IN',
    'Emmet County, MI', 'Erie County, NY', 'Erie County, OH', 'Erie County, PA', 'Florence County, WI',
    'Fond du Lac County, WI', 'Ford County, IL', 'Forest County, WI', 'Franklin County, NY',
    'Fulton County, IN', 'Fulton County, OH', 'Geauga County, OH', 'Genesee County, MI', 'Genesee County, NY',
    'Gladwin County, MI', 'Gogebic County, MI', 'Grand Traverse County, MI', 'Gratiot County, MI',
    'Green Lake County, WI', 'Grundy County, IL', 'Hamilton County, NY', 'Hancock County, OH',
    'Hardin County, OH', 'Henry County, OH', 'Herkimer County, NY', 'Hillsdale County, MI',
    'Houghton County, MI', 'Huron County, MI', 'Huron County, OH', 'Ingham County, MI', 'Ionia County, MI',
    'Iosco County, MI', 'Iron County, MI', 'Iron County, WI', 'Iroquois County, IL', 'Isabella County, MI',
    'Itasca County, MN', 'Jackson County, MI', 'Jasper County, IN', 'Jefferson County, NY',
    'Kalamazoo County, MI', 'Kalkaska County, MI', 'Kane County, IL', 'Kankakee County, IL', 'Kendall County, IL',
    'Kenosha County, WI', 'Kent County, MI', 'Kewaunee County, WI', 'Keweenaw County, MI',
    'Kosciusko County, IN', 'LaGrange County, IN', 'LaPorte County, IN', 'Lake County, IL', 'Lake County, IN',
    'Lake County, MI', 'Lake County, MN', 'Lake County, OH', 'Langlade County, WI', 'Lapeer County, MI',
    'Leelanau County, MI', 'Lenawee County, MI', 'Lewis County, NY', 'Livingston County, MI',
    'Livingston County, NY', 'Lorain County, OH', 'Lucas County, OH', 'Luce County, MI', 'Mackinac County, MI',
    'Macomb County, MI', 'Madison County, NY', 'Manistee County, MI', 'Manitowoc County, WI',
    'Marathon County, WI', 'Marinette County, WI', 'Marion County, OH', 'Marquette County, MI',
    'Marquette County, WI', 'Marshall County, IN', 'Mason County, MI', 'Mecosta County, MI', 'Medina County, OH',
    'Menominee County, MI', 'Menominee County, WI', 'Mercer County, OH', 'Midland County, MI',
    'Milwaukee County, WI', 'Missaukee County, MI', 'Monroe County, MI', 'Monroe County, NY',
    'Montcalm County, MI', 'Montmorency County, MI', 'Muskegon County, MI', 'Newaygo County, MI',
    'Newton County, IN', 'Niagara County, NY', 'Noble County, IN', 'Oakland County, MI', 'Oceana County, MI',
    'Oconto County, WI', 'Ogemaw County, MI', 'Oneida County, NY', 'Oneida County, WI', 'Onondaga County, NY',
    'Ontario County, NY', 'Ontonagon County, MI', 'Orleans County, NY', 'Osceola County, MI',
    'Oscoda County, MI', 'Oswego County, NY', 'Otsego County, MI', 'Ottawa County, MI', 'Ottawa County, OH',
    'Outagamie County, WI', 'Ozaukee County, WI', 'Paulding County, OH', 'Pine County, MN',
    'Portage County, OH', 'Portage County, WI', 'Porter County, IN', 'Potter County, PA', 'Presque Isle County, MI',
    'Pulaski County, IN', 'Putnam County, OH', 'Racine County, WI', 'Richland County, OH',
    'Roscommon County, MI', 'Saginaw County, MI', 'Sandusky County, OH', 'Sanilac County, MI',
    'Schoolcraft County, MI', 'Schuyler County, NY', 'Seneca County, NY', 'Seneca County, OH', 'Shawano County, WI',
    'Sheboygan County, WI', 'Shelby County, OH', 'Shiawassee County, MI', 'St. Clair County, MI',
    'St. Joseph County, IN', 'St. Joseph County, MI', 'St. Lawrence County, NY', 'St. Louis County, MN',
    'Stark County, OH', 'Starke County, IN', 'Steuben County, IN', 'Steuben County, NY',
    'Summit County, OH', 'Tioga County, NY', 'Tompkins County, NY', 'Trumbull County, OH', 'Tuscola County, MI',
    'Van Buren County, MI', 'Van Wert County, OH', 'Vilas County, WI', 'Washington County, WI',
    'Washtenaw County, MI', 'Waukesha County, WI', 'Waupaca County, WI', 'Waushara County, WI',
    'Wayne County, MI', 'Wayne County, NY', 'Wells County, IN', 'Wexford County, MI', 'Whitley County, IN',
    'Will County, IL', 'Williams County, OH', 'Winnebago County, WI', 'Wood County, OH', 'Wyandot County, OH',
    'Wyoming County, NY', 'Yates County, NY'
  ],
  huc8List: [
    '02020001', '02020004', '02040102', '02040104', '02040105', '02040106', '02040203', '02040205',
    '02050102', '02050103', '02050104', '02050105', '02050107', '02050205', '02050301', '02050305',
    '02050306', '02060001', '02060002', '02060003', '02070004', '02070008', '02070009', '04010101',
    '04010102', '04010201', '04010202', '04010301', '04010302', '04020101', '04020102', '04020103',
    '04020104', '04020105', '04020201', '04020202', '04020203', '04030101', '04030102', '04030103',
    '04030104', '04030105', '04030106', '04030107', '04030108', '04030109', '04030110', '04030111',
    '04030112', '04030113', '04030114', '04030201', '04030202', '04030203', '04030204', '04040001',
    '04040002', '04040003', '04050001', '04050002', '04050003', '04050004', '04050005', '04050006',
    '04050007', '04060101', '04060102', '04060103', '04060104', '04060105', '04070003', '04070004',
    '04070005', '04070006', '04070007', '04080101', '04080102', '04080103', '04080104', '04080201',
    '04080202', '04080203', '04080204', '04080205', '04080206', '04090001', '04090002', '04090003',
    '04090004', '04100001', '04100002', '04100003', '04100004', '04100005', '04100006', '04100007',
    '04100008', '04100009', '04100010', '04100011', '04100012', '04100013', '04110001', '04110002',
    '04110003', '04110004', '04120101', '04120102', '04120103', '04130001', '04130002', '04130003',
    '04140101', '04140102', '04140201', '04140202', '04140203', '04140301', '04140302', '04180000',
    '04190000', '04200001', '04200002', '04240002', '04260000', '04270101', '04280002', '04290001',
    '04290002', '04290003', '04290004', '04290005', '04290006', '04290007', '04290008', '04300201',
    '05010001', '05010002', '05010004', '05030102', '05030103', '05040001', '05040002', '05040003',
    '05060001', '05080001', '05120101', '05120104', '05120106', '07010103', '07030001', '07030002',
    '07030003', '07050001', '07050002', '07070001', '07070002', '07070003', '07070005', '07090001',
    '07090002', '07120001', '07120002', '07120003', '07120004', '07120005', '07120006', '07120007',
    '07130002', '09030001', '09030002', '09030005'
  ]
};
