
export var identifyConfig = {



  //
  colorLookup:[
    {
      layer: "exposure",
      value: 1,
      backgroundColor: "#248391",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "exposure",
      value: 2,
      backgroundColor: "#7bb0a3",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "exposure",
      value: 3,
      backgroundColor: "#d4e6b8",
      color: "#343A4F",
      label: "medium",
    },
    {
      layer: "exposure",
      value: 4,
      backgroundColor: "#edd898",
      color: "#e9ecef",
      label: "medium",
    },
    {
      layer: "exposure",
      value: 6,
      backgroundColor: "#c49054",
      color: "#e9ecef",
      label: "high",
    },
    {
      layer: "exposure",
      value: 9,
      backgroundColor: "#9c551f",
      color: "#e9ecef",
      label: "high",
    },
    {
      layer: "exposure",
      value: 255,
      backgroundColor: "#e9ecef",
      color: "#343A4F",
      label: "N/A",
    },
    {
      layer: "asset",
      value: 1,
      backgroundColor: "#b6edf0",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "asset",
      value: 2,
      backgroundColor: "#1f84e0",
      color: "#e9ecef",
      label: "Medium",
    },
    {
      layer: "asset",
      value: 3,
      backgroundColor: "#080a90",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "asset",
      value: 255,
      backgroundColor: "#e9ecef",
      color: "#343A4F",
      label: "N/A",
    },
    {
      layer: "threat",
      value: 1,
      backgroundColor: "#ffebd6",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "threat",
      value: 2,
      backgroundColor: "#e18465",
      color: "#343A4F",
      label: "Medium",
    },
    {
      layer: "threat",
      value: 3,
      backgroundColor: "#c40a0a",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "threat",
      value: 255,
      backgroundColor: "#e9ecef",
      color: "#343A4F",
      label: "N/A",
    },
    {
      layer: "aquatic",
      value: 1,
      backgroundColor: "#FFFFCC",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "aquatic",
      value: 2,
      backgroundColor: "#C7E9B4",
      color: "#343A4F",
      label: "low",
    },
    {
      layer: "aquatic",
      value: 3,
      backgroundColor: "#7FCDBB",
      color: "#343A4F",
      label: "High",
    },
    {
      layer: "aquatic",
      value: 4,
      backgroundColor: "#41B6C4",
      color: "#343A4F",
      label: "Medium",
    },
    {
      layer: "aquatic",
      value: 5,
      backgroundColor: "#1D91C0",
      color: "#e9ecef",
      label: "Medium",
    },
    {
      layer: "aquatic",
      value: 6,
      backgroundColor: "#225EA8",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "aquatic",
      value: 7,
      backgroundColor: "#0C2C84",
      color: "#e9ecef",
      label: "High",
    },{
      layer: "aquatic",
      value: 255,
      backgroundColor: "#e9ecef",
      color: "#343A4F",
      label: "N/A",
    },
    {
     layer: "terristrial",
     value: 1,
     backgroundColor: "#FFFFCC",
     color: "#343A4F",
     label: "Low",
   },
   {
     layer: "terristrial",
     value: 2,
     backgroundColor: "#C7E9B4",
     color: "#343A4F",
     label: "low",
   },
   {
     layer: "terristrial",
     value: 3,
     backgroundColor: "#7FCDBB",
     color: "#343A4F",
     label: "High",
   },
   {
     layer: "terristrial",
     value: 4,
     backgroundColor: "#41B6C4",
     color: "#343A4F",
     label: "Medium",
   },
   {
     layer: "terristrial",
     value: 5,
     backgroundColor: "#1D91C0",
     color: "#e9ecef",
     label: "Medium",
   },
   {
     layer: "terristrial",
     value: 6,
     backgroundColor: "#225EA8",
     color: "#e9ecef",
     label: "High",
   },
   {
     layer: "terristrial",
     value: 7,
     backgroundColor: "#0C2C84",
     color: "#e9ecef",
     label: "High",
   },{
     layer: "terristrial",
     value: 255,
     backgroundColor: "#e9ecef",
     color: "#343A4F",
     label: "N/A",
   },

 ],



};

export default identifyConfig;
