
export var identifyConfig = {
  colorLookup:[
    {
      layer: "exposure",
      value: 1,
      backgroundColor: "#248391",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "exposure",
      value: 2,
      backgroundColor: "#7bb0a3",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "exposure",
      value: 3,
      backgroundColor: "#d4e6b8",
      color: "#343A4F",
      label: "Medium",
    },
    {
      layer: "exposure",
      value: 4,
      backgroundColor: "#edd898",
      color: "#343A4F",
      label: "Medium",
    },
    {
      layer: "exposure",
      value: 6,
      backgroundColor: "#c49054",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "exposure",
      value: 9,
      backgroundColor: "#9c551f",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "exposure",
      value: 255,
      backgroundColor: "#e9ecef",
      color: "#343A4F",
      label: "N/A",
    },
    {
      layer: "asset",
      value: 0,
      backgroundColor: "#b6edf0",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "asset",
      value: 1,
      backgroundColor: "#a1daed",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "asset",
      value: 2,
      backgroundColor: "#8ecaed",
      color: "#343A4F",
      label: "Medium",
    },
    {
      layer: "asset",
      value: 3,
      backgroundColor: "#7abaeb",
      color: "#343A4F",
      label: "High",
    },
    {
      layer: "asset",
      value: 4,
      backgroundColor: "#64aae8",
      color: "#343A4F",
      label: "High",
    },
    {
      layer: "asset",
      value: 5,
      backgroundColor: "#4c99e6",
      color: "#343A4F",
      label: "High",
    },
    {
      layer: "asset",
      value: 6,
      backgroundColor: "#328ae3",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "asset",
      value: 7,
      backgroundColor: "#217bdb",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "asset",
      value: 8,
      backgroundColor: "#2166cf",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "asset",
      value: 9,
      backgroundColor: "#2154c2",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "asset",
      value: 10,
      backgroundColor: "#1d40b5",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "asset",
      value: 11,
      backgroundColor: "#192fa8",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "asset",
      value: 12,
      backgroundColor: "#131f9e",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "asset",
      value: 13,
      backgroundColor: "#080a90",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "asset",
      value: 255,
      backgroundColor: "#090991",
      color: "#343A4F",
      label: "N/A",
    },
    {
      layer: "threat",
      value: 0,
      backgroundColor: "#ffebd6",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "threat",
      value: 1,
      backgroundColor: "#fce5cf",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "threat",
      value: 2,
      backgroundColor: "#fadec5",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "threat",
      value: 3,
      backgroundColor: "#f7d7bc",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "threat",
      value: 4,
      backgroundColor: "#f5d1b5",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "threat",
      value: 5,
      backgroundColor: "#f5cbae",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "threat",
      value: 6,
      backgroundColor: "#f2c4a5",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "threat",
      value: 7,
      backgroundColor: "#f0bc9c",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "threat",
      value: 8,
      backgroundColor: "#edb695",
      color: "#343A4F",
      label: "Medium",
    },
    {
      layer: "threat",
      value: 9,
      backgroundColor: "#ebae8d",
      color: "#343A4F",
      label: "Medium",
    },
    {
      layer: "threat",
      value: 10,
      backgroundColor: "#eba786",
      color: "#343A4F",
      label: "Medium",
    },
    {
      layer: "threat",
      value: 11,
      backgroundColor: "#e8a180",
      color: "#343A4F",
      label: "Medium",
    },
    {
      layer: "threat",
      value: 12,
      backgroundColor: "#e69877",
      color: "#343A4F",
      label: "High",
    },
    {
      layer: "threat",
      value: 13,
      backgroundColor: "#e3906f",
      color: "#343A4F",
      label: "High",
    },
    {
      layer: "threat",
      value: 14,
      backgroundColor: "#e08867",
      color: "#343A4F",
      label: "High",
    },
    {
      layer: "threat",
      value: 15,
      backgroundColor: "#e08063",
      color: "#343A4F",
      label: "High",
    },
    {
      layer: "threat",
      value: 16,
      backgroundColor: "#de775b",
      color: "#343A4F",
      label: "High",
    },
    {
      layer: "threat",
      value: 17,
      backgroundColor: "#db6f53",
      color: "#343A4F",
      label: "High",
    },
    {
      layer: "threat",
      value: 18,
      backgroundColor: "#d9664c",
      color: "#343A4F",
      label: "High",
    },
    {
      layer: "threat",
      value: 19,
      backgroundColor: "#d65f47",
      color: "#343A4F",
      label: "High",
    },
    {
      layer: "threat",
      value: 20,
      backgroundColor: "#d65740",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "threat",
      value: 21,
      backgroundColor: "#d44e39",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "threat",
      value: 22,
      backgroundColor: "#d14734",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "threat",
      value: 23,
      backgroundColor: "#cf3e2d",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "threat",
      value: 24,
      backgroundColor: "#cc3527",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "threat",
      value: 25,
      backgroundColor: "#cc2c21",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "threat",
      value: 26,
      backgroundColor: "#c9251c",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "threat",
      value: 27,
      backgroundColor: "#c71c16",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "threat",
      value: 28,
      backgroundColor: "#c41310",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "threat",
      value: 29,
      backgroundColor: "#080a90",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "threat",
      value: 255,
      backgroundColor: "#c40a0a",
      color: "#343A4F",
      label: "N/A",
    },
    {
      layer: "aquatic",
      value: 1,
      backgroundColor: "#CCE2E8",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "aquatic",
      value: 2,
      backgroundColor: "#8FC8D6",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "aquatic",
      value: 3,
      backgroundColor: "#5EA4BA",
      color: "#343A4F",
      label: "Medium",
    },
    {
      layer: "aquatic",
      value: 4,
      backgroundColor: "#047E91",
      color: "#343A4F",
      label: "Medium",
    },
    {
      layer: "aquatic",
      value: 5,
      backgroundColor: "#095A62",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "aquatic",
      value: 255,
      backgroundColor: "#e9ecef",
      color: "#343A4F",
      label: "N/A",
    },
    {
      layer: "terrestrial",
      value: 1,
      backgroundColor: "#FFE9C4",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "terrestrial",
      value: 2,
      backgroundColor: "#E0C879",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "terrestrial",
      value: 3,
      backgroundColor: "#76974E",
      color: "#343A4F",
      label: "Medium",
    },
    {
      layer: "terrestrial",
      value: 4,
      backgroundColor: "#385B24",
      color: "#343A4F",
      label: "Medium",
    },
    {
      layer: "terrestrial",
      value: 5,
      backgroundColor: "#004908",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "terrestrial",
      value: 255,
      backgroundColor: "#e9ecef",
      color: "#343A4F",
      label: "N/A",
    },
    {
      layer: "hubs",
      value: 1,
      backgroundColor: "#edf8e9",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "hubs",
      value: 2,
      backgroundColor: "#c5ddca",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "hubs",
      value: 3,
      backgroundColor: "#9ec3ac",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "hubs",
      value: 4,
      backgroundColor: "#76a98d",
      color: "#343A4F",
      label: "Medium",
    },
    {
      layer: "hubs",
      value: 5,
      backgroundColor: "#4f8e6f",
      color: "#e9ecef",
      label: "Medium",
    },
    {
      layer: "hubs",
      value: 6,
      backgroundColor: "#277450",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "hubs",
      value: 7,
      backgroundColor: "#005a32",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "hubs",
      value: 255,
      backgroundColor: "#e9ecef",
      color: "#343A4F",
      label: "None",
    },

  ],



};

export default identifyConfig;
