
export var identifyConfig = {



  //
  colorLookup:[
    {
      layer: "exposure",
      value: 1,
      backgroundColor: "#248391",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "exposure",
      value: 2,
      backgroundColor: "#7bb0a3",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "exposure",
      value: 3,
      backgroundColor: "#d4e6b8",
      color: "#343A4F",
      label: "Medium",
    },
    {
      layer: "exposure",
      value: 4,
      backgroundColor: "#edd898",
      color: "#343A4F",
      label: "Medium",
    },
    {
      layer: "exposure",
      value: 6,
      backgroundColor: "#c49054",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "exposure",
      value: 9,
      backgroundColor: "#9c551f",
      color: "#e9ecef",
      label: "high",
    },
    {
      layer: "exposure",
      value: 255,
      backgroundColor: "#e9ecef",
      color: "#343A4F",
      label: "N/A",
    },
    {
      layer: "asset",
      value: 1,
      backgroundColor: "#b6edf0",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "asset",
      value: 2,
      backgroundColor: "#1f84e0",
      color: "#e9ecef",
      label: "Medium",
    },
    {
      layer: "asset",
      value: 3,
      backgroundColor: "#080a90",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "asset",
      value: 255,
      backgroundColor: "#e9ecef",
      color: "#343A4F",
      label: "N/A",
    },
    {
      layer: "threat",
      value: 1,
      backgroundColor: "#ffebd6",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "threat",
      value: 2,
      backgroundColor: "#e18465",
      color: "#343A4F",
      label: "Medium",
    },
    {
      layer: "threat",
      value: 3,
      backgroundColor: "#c40a0a",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "threat",
      value: 255,
      backgroundColor: "#e9ecef",
      color: "#343A4F",
      label: "N/A",
    },
    {
      layer: "aquatic",
      value: 1,
      backgroundColor: "#CCE2E8",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "aquatic",
      value: 2,
      backgroundColor: "#8FC8D6",
      color: "#343A4F",
      label: "Low",
    },
    {
      layer: "aquatic",
      value: 3,
      backgroundColor: "#5EA4BA",
      color: "#343A4F",
      label: "Medium",
    },
    {
      layer: "aquatic",
      value: 4,
      backgroundColor: "#047E91",
      color: "#343A4F",
      label: "Medium",
    },
    {
      layer: "aquatic",
      value: 5,
      backgroundColor: "#095A62",
      color: "#e9ecef",
      label: "High",
    },
    {
      layer: "aquatic",
      value: 255,
      backgroundColor: "#e9ecef",
      color: "#343A4F",
      label: "N/A",
    },
    {
     layer: "terrestrial",
     value: 1,
     backgroundColor: "#FFE9C4",
     color: "#343A4F",
     label: "Low",
   },
   {
     layer: "terrestrial",
     value: 2,
     backgroundColor: "#E0C879",
     color: "#343A4F",
     label: "Low",
   },
   {
     layer: "terrestrial",
     value: 3,
     backgroundColor: "#76974E",
     color: "#343A4F",
     label: "Medium",
   },
   {
     layer: "terrestrial",
     value: 4,
     backgroundColor: "#385B24",
     color: "#343A4F",
     label: "Medium",
   },
   {
     layer: "terrestrial",
     value: 5,
     backgroundColor: "#004908",
     color: "#e9ecef",
     label: "High",
   },
   {
     layer: "terrestrial",
     value: 255,
     backgroundColor: "#e9ecef",
     color: "#343A4F",
     label: "N/A",
   },


   {
    layer: "hubs",
    value: 1,
    backgroundColor: "#FFE9C4",
    color: "#343A4F",
    label: "Low Priority",
  },
  {
    layer: "hubs",
    value: 2,
    backgroundColor: "#E0C879",
    color: "#343A4F",
    label: "Low Priority",
  },
  {
    layer: "hubs",
    value: 3,
    backgroundColor: "#76974E",
    color: "#343A4F",
    label: "Low Priority",
  },
  {
    layer: "hubs",
    value: 4,
    backgroundColor: "#385B24",
    color: "#e9ecef",
    label: "Medium Priority",
  },
  {
    layer: "hubs",
    value: 5,
    backgroundColor: "#004908",
    color: "#e9ecef",
    label: "Medium Priority",
  },
  {
    layer: "hubs",
    value: 6,
    backgroundColor: "#004908",
    color: "#e9ecef",
    label: "High Priority",
  },
  {
    layer: "hubs",
    value: 7,
    backgroundColor: "#004908",
    color: "#e9ecef",
    label: "High Priority",
  },
  {
    layer: "hubs",
    value: 255,
    backgroundColor: "#e9ecef",
    color: "#343A4F",
    label: "Not in a Hub",
  },

 ],



};

export default identifyConfig;
