name: Pull Request Check

on:
  pull_request:
    branches:
      - "*"

jobs:
  pull-request-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Check Code Quality
        run: |
          npm install
          npm run check
